fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib"
    concat: "https://github.com/puppetlabs/puppetlabs-concat"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall"
    limits: "https://github.com/erwbgy/puppet-limits"
    file_concat: "git://github.com/electrical/puppet-lib-file_concat.git"
  symlinks:
   "cvmfs": "#{source_dir}"
